#!/usr/bin/env python3
"""
Export mesh-compressor JSON model to binary C++ header for embedding.

Usage:
    python tools/export_model_cpp.py <model.json|URL> [output.h]

Supports:
    - Local file path: tools/export_model_cpp.py model.json out.h
    - HTTP/HTTPS URL:  tools/export_model_cpp.py https://example.com/model.json out.h

Binary format (MC01):
    char[4]   magic = "MC01"
    uint8     order
    uint16LE  vocab_size
    Vocab entries (vocab_size):
        uint16LE  utf8_len
        uint8[]   utf8_bytes
    Level data (order + 1 levels):
        uint32LE  num_contexts
        Context entries:
            uint16LE  ctx_utf8_len
            uint8[]   ctx_utf8
            uint16LE  num_pairs
            Pair entries:
                uint16LE  vocab_idx
                uint32LE  count
"""

import json
import struct
import sys
from pathlib import Path
from urllib.request import urlopen
from urllib.error import URLError


def is_url(path: str) -> bool:
    return path.startswith("http://") or path.startswith("https://")


def load_json_source(source: str) -> dict:
    """Load JSON model from a local file or URL."""
    if is_url(source):
        print(f"Downloading model from {source}...")
        try:
            with urlopen(source) as resp:
                data = resp.read()
                print(f"  Downloaded {len(data)} bytes")
                return json.loads(data.decode("utf-8"))
        except URLError as e:
            print(f"Error downloading: {e}", file=sys.stderr)
            sys.exit(1)
    else:
        path = Path(source)
        print(f"Loading model from {path}...")
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)


def json_to_binary(model_json: dict) -> bytes:
    """Convert JSON model to binary MC01 format."""
    order = model_json["o"]
    vocab = model_json["v"]
    counts = model_json["c"]

    buf = bytearray()

    # Magic
    buf.extend(b"MC01")

    # Order
    buf.append(order)

    # Vocab size
    buf.extend(struct.pack("<H", len(vocab)))

    # Vocab entries
    for ch in vocab:
        ch_bytes = ch.encode("utf-8")
        buf.extend(struct.pack("<H", len(ch_bytes)))
        buf.extend(ch_bytes)

    # Build vocab index for char -> idx mapping
    vocab_idx = {ch: i for i, ch in enumerate(vocab)}

    # Level data
    for n in range(order + 1):
        level = counts[n] if n < len(counts) else {}
        buf.extend(struct.pack("<I", len(level)))

        for ctx, char_counts in level.items():
            ctx_bytes = ctx.encode("utf-8")
            buf.extend(struct.pack("<H", len(ctx_bytes)))
            buf.extend(ctx_bytes)

            # Filter to valid vocab indices
            pairs = []
            for ch, count in char_counts.items():
                if ch in vocab_idx:
                    pairs.append((vocab_idx[ch], count))

            buf.extend(struct.pack("<H", len(pairs)))
            for idx, count in pairs:
                buf.extend(struct.pack("<H", idx))
                buf.extend(struct.pack("<I", count))

    return bytes(buf)


def binary_to_c_header(data: bytes, var_name: str = "mesh_model_data") -> str:
    """Convert binary data to a C header with a const uint8_t array."""
    lines = []
    lines.append("#pragma once")
    lines.append("")
    lines.append("/**")
    lines.append(" * Auto-generated mesh compressor model data.")
    lines.append(f" * Binary size: {len(data)} bytes ({len(data) / 1024:.1f} KB)")
    lines.append(" * Format: MC01 (N-gram language model for arithmetic coding)")
    lines.append(" * Generated by tools/export_model_cpp.py")
    lines.append(" */")
    lines.append("")
    lines.append("#include <cstddef>")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("#ifdef ARDUINO")
    lines.append("#include <pgmspace.h>")
    lines.append(f"static const uint8_t PROGMEM {var_name}[] = {{")
    lines.append("#else")
    lines.append(f"static const uint8_t {var_name}[] = {{")
    lines.append("#endif")

    # Write data in rows of 16 bytes
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        comma = "," if i + 16 < len(data) else ""
        lines.append(f"    {hex_vals}{comma}")

    lines.append("};")
    lines.append("")
    lines.append(f"static const size_t {var_name}_size = sizeof({var_name});")
    lines.append("")

    return "\n".join(lines)


def prune_model(model: dict, threshold: int = 50, max_order: int = None) -> dict:
    """Prune model by removing low-count contexts and limiting order."""
    order = model["o"]
    if max_order is not None:
        order = min(order, max_order)

    pruned = {"o": order, "v": model["v"], "c": []}
    total_ctx = 0
    for n in range(order + 1):
        d = {}
        min_count = 1 if n == 0 else threshold
        if n < len(model["c"]):
            for ctx, counts in model["c"][n].items():
                t = sum(counts.values())
                if t >= min_count:
                    d[ctx] = counts
        pruned["c"].append(d)
        total_ctx += len(d)

    return pruned, total_ctx


def main():
    import argparse

    parser = argparse.ArgumentParser(
        description="Export mesh-compressor JSON model to binary C++ header"
    )
    parser.add_argument("source", help="Path to model.json or URL")
    parser.add_argument(
        "output", nargs="?", default="mesh_model_data.h", help="Output .h file path"
    )
    parser.add_argument(
        "--threshold",
        type=int,
        default=50,
        help="Min total count for contexts at order >= 3 (default: 50)",
    )
    parser.add_argument(
        "--max-order",
        type=int,
        default=None,
        help="Max n-gram order to export (default: use model order)",
    )
    args = parser.parse_args()

    output_path = Path(args.output)

    model = load_json_source(args.source)

    print(f"  Order: {model['o']}")
    print(f"  Vocab: {len(model['v'])} symbols")
    total_contexts = sum(len(level) for level in model["c"])
    print(f"  Contexts: {total_contexts}")

    if args.threshold != 50 or args.max_order is not None:
        model, total_contexts = prune_model(model, args.threshold, args.max_order)
        print(f"  Pruned: order={model['o']}, threshold={args.threshold}, contexts={total_contexts}")

    print("Converting to binary...")
    binary = json_to_binary(model)
    print(f"  Binary size: {len(binary)} bytes ({len(binary) / 1024:.1f} KB)")

    print(f"Writing C header to {output_path}...")
    header = binary_to_c_header(binary)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(header)

    print(f"  Header size: {output_path.stat().st_size} bytes")
    print("Done!")


if __name__ == "__main__":
    main()
