#!/usr/bin/env python3
"""
Read existing MC01 binary model from C header, prune it, and re-export.

Usage:
    python tools/prune_model.py [--threshold N] [--max-order N] [input.h] [output.h]
"""

import re
import struct
import sys
from pathlib import Path


def parse_c_header_bytes(header_path: str) -> bytes:
    """Extract binary data from C header hex array."""
    text = Path(header_path).read_text()
    # Find all hex values like 0x4d
    hex_vals = re.findall(r"0x([0-9a-fA-F]{2})", text)
    return bytes(int(h, 16) for h in hex_vals)


def read_u16le(data, pos):
    return struct.unpack_from("<H", data, pos)[0]


def read_u32le(data, pos):
    return struct.unpack_from("<I", data, pos)[0]


def parse_mc01(data: bytes) -> dict:
    """Parse MC01 binary to JSON-like dict."""
    assert data[:4] == b"MC01", f"Bad magic: {data[:4]}"
    pos = 4
    order = data[pos]; pos += 1
    vocab_size = read_u16le(data, pos); pos += 2

    vocab = []
    for _ in range(vocab_size):
        ch_len = read_u16le(data, pos); pos += 2
        ch = data[pos:pos+ch_len].decode("utf-8"); pos += ch_len
        vocab.append(ch)

    counts = []
    for n in range(order + 1):
        num_contexts = read_u32le(data, pos); pos += 4
        level = {}
        for _ in range(num_contexts):
            ctx_len = read_u16le(data, pos); pos += 2
            ctx = data[pos:pos+ctx_len].decode("utf-8"); pos += ctx_len
            num_pairs = read_u16le(data, pos); pos += 2
            char_counts = {}
            for _ in range(num_pairs):
                idx = read_u16le(data, pos); pos += 2
                count = read_u32le(data, pos); pos += 4
                char_counts[vocab[idx]] = count
            level[ctx] = char_counts
        counts.append(level)

    return {"o": order, "v": vocab, "c": counts}


def prune_model(model: dict, threshold: int, max_order: int = None) -> tuple:
    """Prune model by removing low-count contexts and limiting order."""
    order = model["o"]
    if max_order is not None:
        order = min(order, max_order)

    pruned = {"o": order, "v": model["v"], "c": []}
    total_ctx = 0
    for n in range(order + 1):
        d = {}
        min_count = 1 if n == 0 else threshold
        if n < len(model["c"]):
            for ctx, char_counts in model["c"][n].items():
                t = sum(char_counts.values())
                if t >= min_count:
                    d[ctx] = char_counts
        pruned["c"].append(d)
        total_ctx += len(d)

    return pruned, total_ctx


def json_to_binary(model: dict) -> bytes:
    """Convert JSON model to MC01 binary."""
    order = model["o"]
    vocab = model["v"]
    counts = model["c"]

    buf = bytearray(b"MC01")
    buf.append(order)
    buf.extend(struct.pack("<H", len(vocab)))

    for ch in vocab:
        ch_bytes = ch.encode("utf-8")
        buf.extend(struct.pack("<H", len(ch_bytes)))
        buf.extend(ch_bytes)

    vocab_idx = {ch: i for i, ch in enumerate(vocab)}

    for n in range(order + 1):
        level = counts[n] if n < len(counts) else {}
        buf.extend(struct.pack("<I", len(level)))
        for ctx, char_counts in level.items():
            ctx_bytes = ctx.encode("utf-8")
            buf.extend(struct.pack("<H", len(ctx_bytes)))
            buf.extend(ctx_bytes)
            pairs = [(vocab_idx[ch], count) for ch, count in char_counts.items() if ch in vocab_idx]
            buf.extend(struct.pack("<H", len(pairs)))
            for idx, count in pairs:
                buf.extend(struct.pack("<H", idx))
                buf.extend(struct.pack("<I", count))

    return bytes(buf)


def binary_to_c_header(data: bytes) -> str:
    """Convert binary to C header."""
    lines = [
        "#pragma once",
        "",
        "/**",
        " * Auto-generated mesh compressor model data.",
        f" * Binary size: {len(data)} bytes ({len(data) / 1024:.1f} KB)",
        " * Format: MC01 (N-gram language model for arithmetic coding)",
        " * Generated by tools/prune_model.py",
        " */",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "#ifdef ARDUINO",
        "#include <pgmspace.h>",
        "static const uint8_t PROGMEM mesh_model_data[] = {",
        "#else",
        "static const uint8_t mesh_model_data[] = {",
        "#endif",
    ]

    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        comma = "," if i + 16 < len(data) else ""
        lines.append(f"    {hex_vals}{comma}")

    lines.extend(["};", "", "static const size_t mesh_model_data_size = sizeof(mesh_model_data);", ""])
    return "\n".join(lines)


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Prune MC01 model from C header and re-export")
    parser.add_argument("input", nargs="?", default="generated/mesh_model_data.h", help="Input .h file")
    parser.add_argument("output", nargs="?", default="generated/mesh_model_data.h", help="Output .h file")
    parser.add_argument("--threshold", type=int, default=500, help="Min total count for contexts at order >= 3")
    parser.add_argument("--max-order", type=int, default=5, help="Max n-gram order")
    parser.add_argument("--dry-run", action="store_true", help="Only show stats, don't write")
    args = parser.parse_args()

    print(f"Reading {args.input}...")
    raw = parse_c_header_bytes(args.input)
    print(f"  Binary: {len(raw)} bytes ({len(raw)/1024:.1f} KB)")

    model = parse_mc01(raw)
    orig_ctx = sum(len(level) for level in model["c"])
    print(f"  Order: {model['o']}, Vocab: {len(model['v'])}, Contexts: {orig_ctx}")

    pruned, new_ctx = prune_model(model, args.threshold, args.max_order)
    print(f"  Pruned: order={pruned['o']}, threshold={args.threshold}, contexts={new_ctx} ({new_ctx*100//orig_ctx}% of original)")

    binary = json_to_binary(pruned)
    print(f"  New binary: {len(binary)} bytes ({len(binary)/1024:.1f} KB), reduction: {100-len(binary)*100//len(raw)}%")

    if args.dry_run:
        print("Dry run — not writing.")
        return

    header = binary_to_c_header(binary)
    Path(args.output).parent.mkdir(parents=True, exist_ok=True)
    Path(args.output).write_text(header)
    print(f"Written to {args.output}")


if __name__ == "__main__":
    main()
